# Generated by Django 3.1.3 on 2020-11-23 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Biz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('slug', models.SlugField()),
                ('business', models.CharField(choices=[('bars', 'Bars'), ('health', 'Health'), ('insurance', 'Insurance'), ('music', 'Music')], default='bars', max_length=50)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('pic', models.FileField(upload_to='media')),
                ('address', models.CharField(blank=True, max_length=200)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('phone', models.CharField(blank=True, max_length=25)),
                ('confirmed', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
