# Generated by Django 3.1.3 on 2020-11-24 00:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='biz',
            old_name='business',
            new_name='category',
        ),
    ]
