# Generated by Django 3.1.3 on 2020-11-26 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0002_auto_20201123_1949'),
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('author', models.CharField(max_length=100)),
                ('headline', models.CharField(max_length=100)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('rating', models.IntegerField(choices=[(1, 'Worst'), (2, 'Not Great'), (3, 'Good'), (4, 'Better'), (5, 'Best')])),
                ('comment', models.CharField(max_length=1000)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.AlterField(
            model_name='biz',
            name='category',
            field=models.CharField(choices=[('restaurants', 'Restaurants'), ('bars', 'Bars'), ('coffee', 'Coffee'), ('food trucks', 'Food Trucks'), ('dive and snorkel', 'Dive Snorkel'), ('night life', 'Night Life'), ('water sports', 'Water Sports'), ('kid camps', 'Kid Camps'), ('music', 'Music'), ('excursions', 'Excursions'), ('places to see', 'Places To See'), ('art and photography', 'Art Photography'), ('clothing', 'Clothing'), ('jewelry', 'Jewelry'), ('home goods', 'Home Goods'), ('other shopping', 'Other Shopping'), ('day care', 'Day Care'), ('schools', 'Schools'), ('college', 'College'), ('other education', 'Other Education'), ('home services', 'Home Services'), ('construction', 'Construction'), ('mechanics', 'Mechanics'), ('other services', 'Other Services'), ('health and medicine', 'Health Medicine'), ('real estate', 'Real Estate'), ('beauty', 'Beauty'), ('transportation', 'Transportation'), ('religion', 'Religion'), ('technology', 'Technology'), ('animals', 'Animals'), ('other businesses', 'Other Businesses')], default='bars', max_length=50),
        ),
    ]
