# Generated by Django 3.1.3 on 2020-11-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0003_auto_20201125_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='biz',
            name='pic',
            field=models.FileField(blank=True, upload_to='media'),
        ),
    ]
