# Generated by Django 3.1.3 on 2020-11-26 02:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('businesses', '0004_auto_20201125_2129'),
    ]

    operations = [
        migrations.AddField(
            model_name='biz',
            name='highCategories',
            field=models.CharField(choices=[('food and drink', 'Food Drink'), ('entertainment', 'Entertainment'), ('shopping', 'Shopping'), ('education', 'Education'), ('professional services', 'Professional Services'), ('other businesses', 'Other Businesses')], default='other businesses', max_length=50),
        ),
    ]
